image: fedora:latest

stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - dnf install libbsd python clang python-pip xorg-x11-server-Xorg xorg-x11-server-devel xorg-x11-drv-evdev-devel xorg-x11-drv-libinput-devel -y
  - python -V
  - uname -a
  - pip install norminette


build:
  stage: build
  script:
    - make
    - make clean
    - make fclean
    - make re

unit-test:
  stage: test
  script:
    - make test

norme:
  stage: test
  script:
    - norminette headers
    - norminette libft
    - norminette sources
