image: fedora:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
  variables:
    CODE_QUALITY_IMAGE: "registry.example.com/codequality-fork:latest"

cache:
  paths:
    - .cache/pip

before_script:
  - dnf install libbsd libbsd-devel python clang python-pip -y
  - dnf groupinstall "X Software Development" -y
  - python -V
  - uname -a
  - pip install norminette

build:
  script:
     - make
     - make clean
     - make fclean
     - make re

test:
  script:
     - make test

norme:
  script:
     - norminette headers
     - norminette libft
     - norminette sources