name: Build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install libbsd-dev
    - name: make
      run: make
    - name: make re
      run: make re
    - name: make clean
      run: make clean
    - name: make fclean
      run: make fclean
