name: Norminette

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  norme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install norminette
    - name: Test norme
      run: |
        norminette headers
        norminette sources
        norminette libft
